name: deploy

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@main

            - name: Build and Deploy
              uses: actions/deploy
              env:
                  COMMIT_EMAIL: lipemg01@gmail.com
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BASE_BRANCH: main
                  DEPLOY_BRANCH: gh-pages
                  BUILD_SCRIPT: yarn && yarn build
                  FOLDER: build